package.json, src/app.ts, yarn.lock
=> feat: add helmet middleware

README.md
=> fix(readme): slightly update wording to address commercial use

firmwares/inovelli/LZW31-SN.json
This is an initial device commit to make sure the formatting is correct and that everything is in order.
=> feat: add firmware update for Inovelli LZW31-SN

firmwares/iblinds/iblinds_V3-1.json, firmwares/iblinds/iblinds_V3.json
Created iblinds manufacturer folder
V3.0:
Added V3.0 Device
Added V3.07 Firmware
V3.1:
Added V3.1 Device
Added V3.12_US Firmware
Added V3.14_US_BETA Firmware
=> feat: Add iblinds V3.0 and V3.1 Firmware updates

firmwares/inovelli/LZW31-SN.json
Added stable version 1.57 for Inovelli LZW31-SN
=> feat: add stable version 1.57 for Inovelli LZW31-SN

firmwares/iblinds/iblinds_V3-1.json, firmwares/iblinds/iblinds_V3.json
#32 Fix
Changed the url to the .gbl files currently hosted on the support site
Remove beta release, current form not in acceptable beta release
=> fix: iblinds firmware files

firmwares/heltun/HE-FT01.json, firmwares/heltun/HE-HLS01.json, firmwares/heltun/HE-HT01.json, firmwares/heltun/HE-RS01.json, firmwares/heltun/HE-TPS01.json, firmwares/heltun/HE-TPS02.json, firmwares/heltun/HE-TPS03.json, firmwares/heltun/HE-TPS04.json, firmwares/heltun/HE-TPS05.json
Information provided by HELTUN via email.
=> Add HELTUN firmwares

firmwares/ultraloq/U-BOLT-PRO-ZWAVE.json
Fixed ultraloq U-BOLT-PRO-ZWAVE door state issue.
=> Add firmware update for U-BOLT-PRO-ZWAVE (Ultraloq)

package.json, yarn.lock
This fixes the integrity checks for redirected downloads
=> fix: update firmware-integrity checker

firmwares/enbrighten-ge/ZW4008_46201.json
=> fix: disable broken Jasco ZW4008 update

firmwares/aeotec/ZW100-A.json, firmwares/aeotec/ZW100-B.json, firmwares/aeotec/ZW100-C.json, firmwares/aeotec/ZWA009-A.json, firmwares/aeotec/ZWA009-B.json, firmwares/aeotec/ZWA009-C.json
- Add ZWA009 V12.01 updates for older V1.X hardware
- Add ZW100 V1.17 updates for V1.14 and above
=> Add Aeotec ZWA009 and ZW100 updates

firmwares/aeotec/ZW162-A.json, firmwares/aeotec/ZW162-C.json, firmwares/aeotec/ZW164-A.json, firmwares/aeotec/ZW164-C.json
- Add ZW162 Doorbell 6 V1.09 update
- Add ZW164 Siren 6 V1.09 update
=> Add Aeotec ZW162 and ZW164 Firmware updates

firmwares/aeotec/ZWA005-A.json, firmwares/aeotec/ZWA005-B.json, firmwares/aeotec/ZWA005-C.json
Add TriSensor V2.21 OTZ Update
=> Add TriSensor V2.21 OTZ Update

firmwares/popp/POPE700397.json, firmwares/popp/POPE700854.json, firmwares/popp/POPE701202.json
- POPE700397 V3.15 Popp Smart Outdoor Plug
- POPE700854 V2.06 Popp Solar Outdoor Siren 2
- POPE701202 V1.02 Popp Mold Detector Sensor
=> Add Popp firmware updates

.github/scripts/check-integrity.cjs, src/maintenance/generateIndex.ts, src/maintenance/upload.ts
Found while testing manually on Windows.
=> fix: use path.resolve instead of path.join

firmwares/aeotec/ZWA024-B.json
V1.6.6 AU/NZ Firmware update file for ZWA024-B MultiSensor 7 added
=> Add Aeotec MultiSensor 7 AU/NZ 

firmwares/aeotec/ZW111-A.json, firmwares/aeotec/ZW111-B.json, firmwares/aeotec/ZW111-C.json, firmwares/aeotec/ZW187-A.json, firmwares/aeotec/ZW187-B.json, firmwares/aeotec/ZW187-C.json
ZW111 Nano Dimmer V2.04 Added (EU code Thanks to @larstobi pull request #101  )
ZW187 Recessed Door Sensor 7 V1.06 Added
closes #101
=> Aeotec Firmware Updates: ZW111 Nano Dimmer v2.4, ZW187 Recessed Door Sensor 7 v1.6

firmwares/aeotec/ZW141-A.json, firmwares/aeotec/ZW141-C.json
@Aeotec-ccheng, can you review this please?
File link obtained from: https://aeotec.freshdesk.com/support/solutions/articles/6000229404-nano-shutter-zw141-update-z-wave-firmware-
=> Add Aeotec ZW141-A EU firmware version 3.6

firmwares/zooz/ZEN55.json
Source: https://www.support.getzooz.com/kb/article/1391-zen55-dc-signal-sensor-change-log/
Firmware from: https://www.support.getzooz.com/kb/article/1158-zooz-ota-firmware-files/
If this looks OK, happy to add a couple more.
=> Add Zooz ZEN55

firmwares/aeotec/ZW187-B.json, firmwares/aeotec/ZWA023-A.json
Firmware Update to resolve an issue with color control when encapsulated by Supervisor.
=> Add Aeotec ZWA023-A

firmwares/zooz/ZAC36-V02.json, firmwares/zooz/ZAC36.json, firmwares/zooz/ZEN15-V02.json, firmwares/zooz/ZEN16-V02.json, firmwares/zooz/ZEN20-V04.json
=> Zooz: add region to ZAC36, add ZAC36-V02, ZEN15-V02, ZEN16-V02, ZEN20-V04

firmwares/zooz/ZEN77-800-LR.json
=> fix: patch version of Zooz ZEN77 800LR

firmwares/zooz/ZEN30-V03.json, firmwares/zooz/ZEN30-V04-800-LR.json
=> Add Zooz ZEN30-V03 and ZEN30-V04-800-LR

firmwares/zooz/ZEN30-V04-800-LR.json
=> Update Zooz ZEN30 800LR to v4.30

firmwares/zooz/ZEN05-V02-800-LR.json, firmwares/zooz/ZEN51.json
=> Add Zooz ZEN05 version 2.20

README.md, src/apiDefinitions.ts, src/routes/api.ts
This PR adds version 4 of the update check API, which supports checking for all updates of all devices in a network in a single request.
=> feat: implement bulk update API endpoint
