zwave-js/firmware-updates

.gitignore, README.md, package.json, src/app.route1.test.ts, src/app.ts, src/lib/apiKeys.ts, src/maintenance/makeAPIKey.ts, src/plugins/checkAPIKey.ts, src/server.ts, yarn.lock
This PR implements API keys that have to be provided with each request to limit access to the API and to tune the rate limiter.
API keys are free for open source, and need to be paid for by commercial projects.
This won't be enforced for now, but it will with zwave-js v10
=> feat: use API keys for auth and rate limiter

package.json, src/lib/cache.ts, src/lib/fs/filesystem.ts, src/lib/shared.ts, src/lib/shared_cloudflare.ts, src/routes/admin.ts, src/routes/api.ts, tsconfig.json, wrangler.toml, yarn.lock
This PR allows us to do two things:
1. cache responses on the server without having to parse and revalidate config files
2. cache responses on the client (assuming the client has proper cache handling), entirely avoiding some duplicate requests
=> feat: cache responses

firmwares/inovelli/LZW31-SN.json
Turns out this is a beta release:
We should mark it as such.
=> fix: move LZW31-SN update to the beta channel

src/durable_objects/RateLimiter.ts
The cost of a handful of persisted values is negligible to millions of writes per month.
=> fix: disable DO destroy alarms for the rate limiter

firmwares/enbrighten-ge/ZW4002_55258.json
Adding latest beta firmware for 55258.
=> Add alternative firmware v0.51 for Enbrighten/GE ZW4002/55258

src/lib/cache.ts, src/lib/fs/cachedR2FS.ts, src/maintenance/upload.ts, src/routes/admin.ts, src/routes/api.ts, src/worker.ts, wrangler.toml
Prior to this PR, we used KV to cache files read from R2 in order to achieve lower latency. However this adds unnecessary cost for KV reads, so we now use the Cache API for this instead.
=> feat: use cache API to cache R2 responses, not KV

.github/scripts/check-integrity.cjs, README.md, firmwares/_example.json, firmwares/iblinds/iblinds_V3-1.json, firmwares/iblinds/iblinds_V3.json, schemas/firmware.json, src/apiDefinitions.ts, src/lib/configSchema.ts, src/routes/api.ts
With this change, we have the capability to specify which region an update belongs to. Since filtering updates by region requires region information from the client, this feature is opt-in through the new `/v3` API endpoint. The v1 and v2 endpoints will not return any updates which have a region specified. The v3 endpoint will only return updates without any region information (considered applicable to all regions) as well as updates matching the provided region.
fixes: #41
=> feat: regional updates

package.json, src/middleware/withAPIKey.ts, yarn.lock
This should cut the other half of KV reads down by a ton.
=> chore: cache reads from API key KV store

package.json, src/middleware/withAPIKey.ts, yarn.lock
The BetterKV cache approach didn't seem to work, so we're caching the KV reads the same way we do for the R2 reads now.
=> fix: cache API keys directly, without BetterKV

firmwares/inovelli/LZW31.json
[reference manufacturers website for firmware details](https://support.inovelli.com/portal/en/kb/articles/firmware-change-log-lzw31-dimmer-switch-black-series#Beta)
=> feat: add Inovelli LZW31 v1.52 (beta) and v1.57

firmwares/ultraloq/U-BOLT-PRO-ZWAVE.json
change z-wave firmware from beta channel to stable
-Fixed door state issue.
=> change Ultraloq Z-Wave Lock firmware from beta channel to stable

firmwares/inovelli/VZW31-SN.json
=> Inovelli VZW31-SN fw 1.2 Update

firmwares/shelly/qnpl-001X12UK.json, firmwares/shelly/qnsh-001P10.json, firmwares/shelly/qnsw-001P16.json, firmwares/shelly/qnsw-001X16.json, firmwares/shelly/qnsw-002P16.json
FW for devices Wave 1, Wave 1PM, Wave 2PM, Wave Shutter, Wave Plug UK
=> Added 5 Shelly Qubino wave devices firmware update

firmwares/zooz/ZAC38.json, firmwares/zooz/ZEN53.json
=> Add EU version for Zooz ZEN53, ZAC38

firmwares/zooz/ZEN74.json
=> Update Zooz ZEN74 min version

firmwares/shelly/qnsw-002P16.json
=> Remove Shelly Wave 2PM 12.04 firmware update

firmwares/aeotec/ZW175-C.json
This adds firmware 1.3 for the **EU version** of the **Aeotec Smart Switch 7** which was [recently made available](https://aeotec.freshdesk.com/support/solutions/articles/6000270359-update-smart-switch-7-eu-v1-03-zw175-c-). It fixes a rather annoying bug where the change threshold settings don't do anything when the initial value is above 0 (at least for the Watts sensor, though I'm not entirely sure other sensors were not affected as well).
@Aeotec-ccheng Could you please review this PR?
=> Add Aeotec ZW175-C EU firmware version 1.3

firmwares/zooz/ZEN72-800-LR.json, firmwares/zooz/ZEN77-800-LR.json
=> Add Country and Version for Zooz ZEN77-800-LR and ZEN72-800-LR

firmwares/zooz/ZEN51.json, firmwares/zooz/ZEN52.json, firmwares/zooz/ZEN54.json, firmwares/zooz/ZEN71-800-LR.json, firmwares/zooz/ZEN71-V02.json, firmwares/zooz/ZEN76-800.json, firmwares/zooz/ZEN76-V02.json
=> Update: ZEN54, ZEN51, ZEN52, ZEN76-V02, ZEN76-800, ZEN71-V02, ZEN71-800

firmwares/zooz/ZEN71-V03-800-LR.json
=> Zooz ZEN71 800LR: add version: 3.50.0

firmwares/zooz/ZEN77-V04-800-LR.json
=> Zooz ZEN77 800LR: add version 4.60

firmwares/zooz/ZEN76-V03-800-LR.json
=> Zooz ZEN76 800LR: add version 3.50

firmwares/zooz/ZEN51.json
=> Add productType `0x0104` for Zooz ZEN51

firmwares/shelly/qnsw-002P16.json
=> Add Shelly Wave 2PM, firmware 15.0

firmwares/zooz/ZSE11-V01.json, firmwares/zooz/ZSE11-V02-800-LR.json
=> Add Zooz ZSE11 2.10.0 (800LR) and 1.30 firmware updates

firmwares/zooz/ZEN72-V03-800-LR.json
3.60.0 existed too at some point as per the [changelog ](https://www.support.getzooz.com/kb/article/849-zen72-dimmer-change-log/)but I can't find the download link anywhere and doing the replacement in the url leads to a 404 so I just skipped it.
=> Add Zooz ZEN72-V03-800-LR firmware version 3.70.0

firmwares/zooz/ZSE44-V02.json
=> Add Zooz ZSE44-V02 firmware version 2.20.1 (US and EU)

firmwares/zooz/ZEN17-V02-800-LR.json
=> Add Zooz ZEN17-V02-800-LR firmware version 2.20.0 (US and EU)

firmwares/zooz/ZEN76-V03-800-LR.json
=> Add Zooz ZEN76 V03 firmware version 3.60.0
